### ISSUE TITLE
LDC Does Not Allow auto To Infer void Types

### ISSUE THREAD

**Issue by JackStouffer** [ldc-developers/ldc#1009]
I'm not sure if this is an error in DMD or LDC, but the following code complies in DMD (v2.067) but not in LDC (0.15.0):

```
import core.thread;

void test() {}

void main() {
    auto writer_one = new Thread(&test).start();
}
```

```
$ ldc test.d
test.d(6): Error: variable test.main.writer_one type void is inferred from initializer (new Thread(& test, 0LU)).start(), and variables cannot be of type void
test.d(6): Error: expression (new Thread(& test, 0LU)).start() is void and has no value
```

**Comment by klickverbot** [comment]
Neither, in fact: The code compiles with the 2.067 branch of LDC. :)
