### ISSUE TITLE
Linker Error: undefined reference to opEquals in __xopEquals

### ISSUE THREAD

**Issue by PaulDiraq** [ldc-developers/ldc#2199]
I am getting a linker error for the following procedure:

in file modA.d 

```
module modA;

struct A(size_t kind)
{
  bool opEquals(size_t rkind)( A!(rkind) rslice)  const
      {
	return true;
      }
}
```

in file modv.d

```
module modv;
import modA;

void v(A!(1) xsl, A!(1 ) ysl) ;
```

in file main.d:

```
import modv;
import modA;

void main(){
  auto A1 = A!(1)();
  destroy(A1);
}

```
trying then to compile it (modA as a library):

ldc2  -Isource/  -lib -oflibmodA.a  -O3 source/modA.d

ldc2 -I.  main.d -L=-lmodA -L=-L./

results in the following error:
```
main.o: In function `_D4modA10__T1AVmi1Z1A11__xopEqualsFKxS4modA10__T1AVmi1Z1AKxS4modA10__T1AVmi1Z1AZb':
main.d:(.text._D4modA10__T1AVmi1Z1A11__xopEqualsFKxS4modA10__T1AVmi1Z1AKxS4modA10__T1AVmi1Z1AZb[_D4modA
10__T1AVmi1Z1A11__xopEqualsFKxS4modA10__T1AVmi1Z1AKxS4modA10__T1AVmi1Z1AZb]+0x17): undefined reference to `_D4modA10__T1
AVmi1Z1A17__T8opEqualsVmi1Z8opEqualsMxFNaNbNiNfS4modA10__T1AVmi1Z1AZb'                                                 
collect2: error: ld returned 1 exit status
Error: /usr/bin/gcc failed with status: 1
```

the symbols can be demangled to :
```
in function
bool modA.A!(1uL).A.__xopEquals(ref const(modA.A!(1uL).A), ref const(modA.A!(1uL).A))
...
undefined reference to:
const(pure nothrow @nogc @safe bool function(modA.A!(1uL).A)) modA.A!(1uL).A.opEquals!(1uL).opEquals
```

If I understand it correctly, it occurs because the signature of opEquals doesn't fully fit the signature expected in __xopEquals: I would then expect the compiler to auto generate a correct opEquals. 

version:
```
LDC - the LLVM D compiler (1.3.0git-b82d87d):
  based on DMD v2.073.2 and LLVM 3.9.0
  built with LDC - the LLVM D compiler (0.17.5git-64a274a)
  Default target: x86_64-unknown-linux-gnu
  Host CPU: haswell
```

**Comment by kinke** [comment]
Thanks for the report. Does it work with DMD 2.073?

**Comment by PaulDiraq** [comment]
Just tried it with DMD 2.075 and it fails. I will try 2.073 later.

By the way, the -O3 for library compilation is needed either for failing.

**Comment by kinke** [comment]
@9il: You might be hitting this.

**Comment by kinke** [comment]
I just checked this with DMD 2.076.1 and LDC 1.5-beta1. The required `opEquals!1()` definition ends up in the object file for `modv.d` for both compilers, so if you include that one for linking, it works, otherwise it fails. As `main.d` imports `modv.d`, assuming the according object will make it to the linker command line seems safe. If you still think this is a bug and not a byproduct of the front-end's template culling mechanism, please open a DMD ticket.
