### PR TITLE
Put debuginfo on GEP instead of on the alloca with an offset.

### PR DESCRIPTION
**Pull request by JohanEngelen**
Resolves issue #1933 .

It's the same workaround for an LLVM bug (I think it's a bug) as #1646 .

~~Working on reducing the original testcase further so it doesn't rely on Phobos; will add later.~~ Original testcase added.

### CODE REVIEW

**Comment by JohanEngelen** [comment]
Any comments?
(it seems to work, and it fixes the bug)

**Comment by rainers** [comment]
Does this also fix https://github.com/ldc-developers/dmd-testsuite/blob/ldc/runnable/gdb10311.d which is currently disabled https://github.com/ldc-developers/dmd-testsuite/blob/ldc/Makefile#L156?
This test case also showed wrong values for the closure variable while executing the nested function.

File: gen/nested.cpp [hunk 1]
```diff
@@ -154,8 +151,10 @@ DValue *DtoNestedVariable(Loc &loc, Type *astype, VarDeclaration *vd,
   }
 
   if (dwarfValue && global.params.symdebug) {
-    gIR->DBuilder.EmitLocalVariable(dwarfValue, vd, nullptr, false, true,
-                                    dwarfAddr);
+    // Because we are passing a GEP instead of an alloca to
+    // llvm.dbg.declare, we have to make the address dereference explicit.
+    gIR->DBuilder.OpDeref(dwarfAddr);
+    gIR->DBuilder.EmitLocalVariable(gep, vd, nullptr, false, true, dwarfAddr);
```
Comment (kinke) [inline gen/nested.cpp]: If going with this, please do it properly and get rid of `dwarfValue` and make sure the only DWARF op is this last deref (otherwise it's surely wrong if the variable is an outer frame, as there's additional offsetting and dereferencing going on).

Comment (JohanEngelen) [inline gen/nested.cpp]: I don't understand. Are you saying that the original code is wrong? (this PR is just a different way of doing the same thing as the original code is doing)

Comment (kinke) [inline gen/nested.cpp]: As far as I understand this, we previously used the nested frame alloca as `LLValue* dwarfValue` for the DI declaration. We then represented the actual variable location via DWARF expressions based on that alloca, such as loading the first frame field for the outermost frame address and then further offsetting into that outer frame to get the address of a nested variable in the outermost scope. That's why the code does every offset and load twice, once for the actual `LLValue*` and then via DWARF ops for the debuginfo declaration.
Now with your workaround consisting in passing the actual variable address directly, a GEP, in combination with an explicit DWARF deref instead of an alloca with a potentially complex DWARF expression, we don't need the previous DWARF ops [here](https://github.com/ldc-developers/ldc/pull/1963/files#diff-8f5a14f6e1ae81e4570abcb00d35ebc5R124).

I'd rather favor looking into what we may do wrong wrt. DWARF expressions instead of using the GEP, as the docs state it should be an alloca, I guess because that should make it easier to keep debug infos for variables when optimizations (such as alloca elisions) are enabled (and in fact this transformation of debuginfos seems to cause #1933). I did a very quick test with `DW_OP_bit_piece` instead of `DW_OP_plus` for the offset, but that quickly produced an LLVM assertion, and I didn't pursue it further (and am currently lacking time).

Comment (JohanEngelen) [inline gen/nested.cpp]: Ahhh, yes you are right, good catch. Will work on a fix tonight. Hope I can test things a little.....

Back then, I also tried using `DW_OP_bit_piece` but failed after trying for a long time. I think these are all LLVM bugs. Clang uses a different mechanism (defines a struct for each nested frame) and so I think the optimization passes are not tested very well for our fancy DW_OP constructs.

I also do not have much time at the moment. I just hope we can release soon. So I'm happy to fix the bug right now, and postpone looking into how to use LLVM properly / file LLVM bugs later.

File: gen/nested.cpp [hunk 2]
```diff
@@ -135,27 +119,33 @@ DValue *DtoNestedVariable(Loc &loc, Type *astype, VarDeclaration *vd,
...
+  LLValue *gep = DtoGEPi(val, 0, idx, vd->toChars());
+  val = gep;
   IF_LOG {
     Logger::cout() << "Addr: " << *val << '\n';
     Logger::cout() << "of type: " << *val->getType() << '\n';
   }
   if (!isSpecialRefVar(vd) && (byref || vd->isRef() || vd->isOut())) {
     val = DtoAlignedLoad(val);
-    // dwarfOpDeref(dwarfAddr);
+    gIR->DBuilder.OpDeref(dwarfAddrOps);
```
Comment (kinke) [inline gen/nested.cpp]: Thanks for the clean-up, LGTM. Are you sure about this particular change? Just asking because we give ref/out variables a special reference-debuginfo type [here](https://github.com/ldc-developers/ldc/blob/master/gen/dibuilder.cpp#L1092).

**Comment by kinke** [comment]
@rainers: No, the value is still `<optimized out>` with https://github.com/ldc-developers/ldc/pull/1963/commits/4b68abbd44528d06666fa0da8143faa66ef31bc3 on Ubuntu 16.04.

**Comment by rainers** [comment]
> No, the value is (still?) <optimized out>

Too bad. Thanks for testing.

File: gen/nested.cpp (hunk 2 above)
Comment (JohanEngelen) [inline gen/nested.cpp]: No, I am not sure at all about that change. Thanks for pointing out the code where the reference type is set for the debug info.

Comment (JohanEngelen) [inline gen/nested.cpp]: Fixed.

**Comment by kinke** [comment]
I've added 2 more temptative fixes: https://github.com/kinke/ldc/commits/fix1933

Those will need some more testing though.

**Comment by kinke** [comment]
The 2nd one above is redundant, as special-ref variables have the ref storage class anyway, so they are already correctly declared as references, and `foreach (ref e; range)` works.

Sadly, there's a regression wrt. captured `this` though for gdb:
```D
struct S
{
    int a;

    void foo()
    {
        void bar()
        {
            a = 456; // <-- breakpoint here
        }
        bar();
    }
}

void main()
{
    auto s = new S(123);
    s.foo();
    assert(s.a == 456);
}
```

gdb shows `this` and `a` as `<optimized out>` with this PR (and my first tentative fix as well), while it worked fine before:
```
(gdb) info locals
this = @0x7ffff7ed6000: {a = 123}
(gdb) print this
$1 = (S &) @0x7ffff7ed6000: {a = 123}
(gdb) print this.a
$2 = 123
(gdb) print a
$3 = 123
```

**Comment by JohanEngelen** [comment]
:( 

Can we live with the regression and get this in, possibly with your extra fix, to speed-up release?  (I don't have much time to delve into this issue :/ )

**Comment by kinke** [comment]
I can't really make my mind up whether this fix for `-O<N > 0> -g` (easily worked around with `-disable-verify`) is worth it at the expense of that regression, which happens for regular `-g` builds and should thus have a far more wide-spread impact.

**Comment by JohanEngelen** [comment]
I'll try to test a little with lldb.
Perhaps this PR just completely breaks the generated debuginfo? (and by accident removes the LLVM assert).

**Comment by kinke** [comment]
I don't think it's that bad. I assumed the mostly enabled gdb tests in dmd-testsuite would cover regular closure variables, but since `vthis` apparently isn't, I'm not so sure anymore.

**Comment by JohanEngelen** [comment]
My line of reasoning was: better to have bad debug info :( , then to have LDC crash on a popular project (`-g -O` is quite common I think). The workaround `-disable-verify` is not well-known enough. I thought we had pretty much completely dysfunctional debuginfo in the previous release, iirc (llvm >= 3.8)?

**Comment by kinke** [comment]
If `-O -g` is indeed rather common, it definitely makes sense to include this (+ my 2 tiny extensions) in 1.1.

The cherry-picks onto `release-1.1.0` were rather conservative, so I don't expect any troubles from the few hotfixes. @JohanEngelen @klickverbot @smolt: Enough time to prepare the final 1.1 release this week? And any plans wrt. moving to a newer front-end (2.073.0?)?

**Comment by JohanEngelen** [comment]
OK, so let's get this in. Will you do the merge @kinke ?

Yes, let's finalize the 1.1.0 release. I can easily prepare the Mac packages this week.

> any plans wrt. moving to a newer front-end (2.073.0?)

I have not worked on it because I am working on getting Weka up to LDC 1.1.0. Because I think it is very valuable to test LDC master (or something close to it) on Weka's codebase, I did not yet work on moving to newer frontend versions. But once I am done with Weka->1.1.0, I will probably start working on moving LDC to 2.072 soon after, and possibly 2.073 immediately after.

**Comment by JohanEngelen** [comment]
(about merging: i meant including your 2 extra fixes)

**Comment by kinke** [comment]
Merged as part of #1984.

**Comment by smolt** [comment]
> Enough time to prepare the final 1.1 release this week?

I won't probably have time until weekend if curious about me creating the armv7hf release.  I just looked at the ldc-scripts and they appear to support arm, so would try that.  Do you all make the final binary by having ldc recompiling itself?

**Comment by JohanEngelen** [comment]
> make the final binary by having ldc recompiling itself

Yes :-)

**Comment by kinke** [comment]
https://github.com/ldc-developers/ldc-scripts/commit/ddc0c5ce3f42ce912ee834187963367a27a964ff should take care of bootstrapping LDC with itself. https://github.com/ldc-developers/ldc-scripts/commit/6c6f8f29776a56861ee69a33191436578f48ed69 reduces the variables to set manually. ;)

The release draft is up and I've added the few bugfixes since beta6, feel free to improve it. I'll do the tagging after dinner, so that we can build & upload the packages over the next days/weekend and then finally publish it officially.

**Comment by JohanEngelen** [comment]
nice

**Comment by kinke** [comment]
> I will probably start working on moving LDC to 2.072 soon after

I've just started merging 2.072.2 into druntime for a start just so you all know.

**Comment by smolt** [comment]
I have kicked off an armv7hf build of 1.1.0 on a Raspberry Pi 3 using ldc-scripts.  First time trying these scripts, might take me a couple cycles to get it right.  And Pi 3, though way fast than Pi 1, still is slow compared to x86 machines.  BTW, I am thinking of also building ldc in a Raspbian compatible way (armv6 instructions), which supports all Pi versions (earlier Pi 1 is not armv7).  Is there interest in including that binary?

**Comment by smolt** [comment]
Something I just realized.  By building on Raspbian, the system gcc only generates armv6 instructions by default.  This means C/C++ portions of LDC, druntime, and phobos will not use armv7 instructions.  It will run ok because armv7 is superset of armv6, and D parts will use armv7 instructions.  I could play with C flags when I build LLVM and LDC, but have a feeling it might take some time to get right.

**Comment by kinke** [comment]
If it defaults to armv6, I think an armv6 LDC package makes most sense. Including the `-mtriple=...` in CMake variables `D_COMPILER_FLAGS` (LDC D parts) and `D_FLAGS` (runtime libs) may be enough to do the job.

**Comment by kinke** [comment]
Btw I've started merging the 2.072.2 ddmd front-end and am in the process of ironing out the most obvious compilation errors. I'll open a corresponding branch in the next couple of days for collaboration.
