### ISSUE TITLE
Error building from git

### ISSUE THREAD

**Issue by CyberShadow** [ldc-developers/ldc#1900]
Trying to build the Arch Linux AUR `ldc-git` package results in:

```
[  9%] Built target ldmd-git
/home/vladimir/.cache/pacaur/ldc-git/src/ldc/ddmd/dtemplate.d(3688): Deprecation: Using the result of a comma expression is deprecated
/home/vladimir/.cache/pacaur/ldc-git/src/ldc/ddmd/expression.d(12414): Deprecation: Using the result of a comma expression is deprecated
/home/vladimir/.cache/pacaur/ldc-git/src/ldc/ddmd/expression.d(12415): Deprecation: Using the result of a comma expression is deprecated
/home/vladimir/.cache/pacaur/ldc-git/src/ldc/ddmd/func.d(1378): Deprecation: Using the result of a comma expression is deprecated
/home/vladimir/.cache/pacaur/ldc-git/src/ldc/ddmd/func.d(2454): Deprecation: Using the result of a comma expression is deprecated
/home/vladimir/.cache/pacaur/ldc-git/src/ldc/ddmd/parse.d(2683): Deprecation: Using the result of a comma expression is deprecated
/home/vladimir/.cache/pacaur/ldc-git/src/ldc/ddmd/root/rmem.d(190): Deprecation: alias object.TypeInfo.init is deprecated - Please use initializer instead.
/home/vladimir/.cache/pacaur/ldc-git/src/ldc/ddmd/root/rmem.d(191): Deprecation: alias object.TypeInfo.init is deprecated - Please use initializer instead.
/home/vladimir/.cache/pacaur/ldc-git/src/ldc/ddmd/root/rmem.d(191): Deprecation: alias object.TypeInfo.init is deprecated - Please use initializer instead.
/home/vladimir/.cache/pacaur/ldc-git/src/ldc/ddmd/root/rmem.d(206): Deprecation: alias object.TypeInfo.init is deprecated - Please use initializer instead.
/home/vladimir/.cache/pacaur/ldc-git/src/ldc/ddmd/root/rmem.d(213): Deprecation: alias object.TypeInfo.init is deprecated - Please use initializer instead.
/home/vladimir/.cache/pacaur/ldc-git/src/ldc/ddmd/root/rmem.d(213): Deprecation: alias object.TypeInfo.init is deprecated - Please use initializer instead.
/home/vladimir/.cache/pacaur/ldc-git/src/ldc/ddmd/utf.d(311): Deprecation: Using the result of a comma expression is deprecated
[  9%] Generating bin/ldc-git
/home/vladimir/.cache/pacaur/ldc-git/src/ldc/build/bin/ldc-git.o: In function `_D3std5array29__T19appenderNewCapacityVmi1Z19appenderNewCapacityFNaNbNiNfmmZm':
/home/vladimir/.cache/pacaur/ldc-git/src/ldc/driver/main.d:(.text._D3std5array29__T19appenderNewCapacityVmi1Z19appenderNewCapacityFNaNbNiNfmmZm+0x3f): undefined reference to `_D4core5bitop19__T8softScanTmVbi0Z8softScanFNaNbNiNfmZi'
/home/vladimir/.cache/pacaur/ldc-git/src/ldc/build/bin/ldc-git.o: In function `_D3std5array30__T19appenderNewCapacityVmi16Z19appenderNewCapacityFNaNbNiNfmmZm':
/home/vladimir/.cache/pacaur/ldc-git/src/ldc/driver/main.d:(.text._D3std5array30__T19appenderNewCapacityVmi16Z19appenderNewCapacityFNaNbNiNfmmZm+0x43): undefined reference to `_D4core5bitop19__T8softScanTmVbi0Z8softScanFNaNbNiNfmZi'
/home/vladimir/.cache/pacaur/ldc-git/src/ldc/build/bin/ldc-git.o: In function `_D6driver13cache_pruning11CachePruner7doPruneMFZv':
/home/vladimir/.cache/pacaur/ldc-git/src/ldc/driver/main.d:(.text._D6driver13cache_pruning11CachePruner7doPruneMFZv+0x6f): undefined reference to `_D3std4file10dirEntriesFAyaAyaE3std4file8SpanModebZS3std9algorithm9iteration125__T12FilterResultS80_D3std4file10dirEntriesFAyaAyaE3std4file8SpanModebZ1fMFNaNbS3std4file8DirEntryZbTS3std4file11DirIteratorZ12FilterResult'
/home/vladimir/.cache/pacaur/ldc-git/src/ldc/build/bin/ldc-git.o: In function `_D6driver13cache_pruning11CachePruner188__T14pruneForExpiryTS3std9algorithm9iteration125__T12FilterResultS80_D3std4file10dirEntriesFAyaAyaE3std4file8SpanModebZ1fMFNaNbS3std4file8DirEntryZbTS3std4file11DirIteratorZ12FilterResultZ14pruneForExpiryMFS3std9algorithm9iteration125__T12FilterResultS80_D3std4file10dirEntriesFAyaAyaE3std4file8SpanModebZ1fMFNaNbS3std4file8DirEntryZbTS3std4file11DirIteratorZ12FilterResultJAS3std4file8DirEntryJmZv':
/home/vladimir/.cache/pacaur/ldc-git/src/ldc/driver/main.d:(.text._D6driver13cache_pruning11CachePruner188__T14pruneForExpiryTS3std9algorithm9iteration125__T12FilterResultS80_D3std4file10dirEntriesFAyaAyaE3std4file8SpanModebZ1fMFNaNbS3std4file8DirEntryZbTS3std4file11DirIteratorZ12FilterResultZ14pruneForExpiryMFS3std9algorithm9iteration125__T12FilterResultS80_D3std4file10dirEntriesFAyaAyaE3std4file8SpanModebZ1fMFNaNbS3std4file8DirEntryZbTS3std4file11DirIteratorZ12FilterResultJAS3std4file8DirEntryJmZv+0x5c): undefined reference to `_D3std9algorithm9iteration125__T12FilterResultS80_D3std4file10dirEntriesFAyaAyaE3std4file8SpanModebZ1fMFNaNbS3std4file8DirEntryZbTS3std4file11DirIteratorZ12FilterResult7opSliceMFNbZS3std9algorithm9iteration125__T12FilterResultS80_D3std4file10dirEntriesFAyaAyaE3std4file8SpanModebZ1fMFNaNbS3std4file8DirEntryZbTS3std4file11DirIteratorZ12FilterResult'
/home/vladimir/.cache/pacaur/ldc-git/src/ldc/driver/main.d:(.text._D6driver13cache_pruning11CachePruner188__T14pruneForExpiryTS3std9algorithm9iteration125__T12FilterResultS80_D3std4file10dirEntriesFAyaAyaE3std4file8SpanModebZ1fMFNaNbS3std4file8DirEntryZbTS3std4file11DirIteratorZ12FilterResultZ14pruneForExpiryMFS3std9algorithm9iteration125__T12FilterResultS80_D3std4file10dirEntriesFAyaAyaE3std4file8SpanModebZ1fMFNaNbS3std4file8DirEntryZbTS3std4file11DirIteratorZ12FilterResultJAS3std4file8DirEntryJmZv+0xfb): undefined reference to `_D3std9algorithm9iteration125__T12FilterResultS80_D3std4file10dirEntriesFAyaAyaE3std4file8SpanModebZ1fMFNaNbS3std4file8DirEntryZbTS3std4file11DirIteratorZ12FilterResult5frontMFNdZS3std4file8DirEntry'
/home/vladimir/.cache/pacaur/ldc-git/src/ldc/driver/main.d:(.text._D6driver13cache_pruning11CachePruner188__T14pruneForExpiryTS3std9algorithm9iteration125__T12FilterResultS80_D3std4file10dirEntriesFAyaAyaE3std4file8SpanModebZ1fMFNaNbS3std4file8DirEntryZbTS3std4file11DirIteratorZ12FilterResultZ14pruneForExpiryMFS3std9algorithm9iteration125__T12FilterResultS80_D3std4file10dirEntriesFAyaAyaE3std4file8SpanModebZ1fMFNaNbS3std4file8DirEntryZbTS3std4file11DirIteratorZ12FilterResultJAS3std4file8DirEntryJmZv+0x3ca): undefined reference to `_D3std9algorithm9iteration125__T12FilterResultS80_D3std4file10dirEntriesFAyaAyaE3std4file8SpanModebZ1fMFNaNbS3std4file8DirEntryZbTS3std4file11DirIteratorZ12FilterResult8popFrontMFZv'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/ldc-git.dir/build.make:62: bin/ldc-git] Error 1
make[1]: *** [CMakeFiles/Makefile2:105: CMakeFiles/ldc-git.dir/all] Error 2
make: *** [Makefile:161: all] Error 2
```

Same package worked on 2016-10-22, so unless it's something wrong with my system or the AUR package, it might be a regression.

**Comment by kinke** [comment]
Which D host compiler do you use?
As the CI tests make sure LDC can be built with DMD (2.071 and 2.072 I think) and LDC (0.17.2, 1.0, latest beta, and itself), I guess the issue is the AUR package.

**Comment by CyberShadow** [comment]
Oops, I forgot I had a DMD built from git in my PATH. Somehow didn't realize makepkg would be using that. Builds fine with 2.071.2, thanks :)
