### ISSUE TITLE
Internal Compiler Error: Invalid struct cast from <struct name> to bool

### ISSUE THREAD

**Issue by n8sh** [ldc-developers/ldc#3159]
This code compiles with all versions of DMD from 2.060 onward but LDC2 1.17.0 crashes trying to compile it:
https://run.dlang.io/is/gwsTIm
```d
class C {
    struct S {
        C value;
        alias value this;
    }
    static T = S();
    static F = S();
}
void main(string[] args)
{
    if (args ? C.T : C.F)
        assert(args);
}

```
Error is:
>filename.d(11): Error: Internal Compiler Error: Invalid struct cast from S to bool

**Comment by kinke** [comment]
It works when adding the `.value` manually, the `-vcg-ast` output is identical in that case.

**Comment by kinke** [comment]
That's a buggy AST - the ternary expression in the if condition is rewritten as `args ? C.T.value : C.F.value` - of type `S` (while both branches are `C`)! We then try to cast that `S` result to a bool for the condition during codegen, where `alias this` isn't handled.

The fix is either a `(args ? C.T : C.F).value` rewrite, or fixing up the `CondExp` type when rewriting its branches. Happens at least since LDC v1.12, so no recent regression.
