### ISSUE TITLE
__vector << int produce ICE, should be illegal?

### ISSUE THREAD

**Issue by p0nce** [ldc-developers/ldc#3606]
The following program crashes LDC 1.24.0 and below too:

```d
import core.simd;
void fun()
{
    int4 A;
    A = A << 8;
}
```

Output with LDC 1.24:
```
#1 with ldc beta
sext source and destination must both be a vector or neither
  %5 = sext i32 8 to <4 x i32>
in function _D7example3funFAAyaZv
LLVM ERROR: Broken function found, compilation aborted!
/opt/compiler-explorer/ldcbeta/bin/ldc2[0x33f03d4]
Compiler returned: 255
```

DMD output is correct:
```
<source>(6): Error: incompatible types for `(A) << (8)`: `__vector(int[4])` and `int`
Compiler returned: 1
```

Interestingly it used to work in LDC 1.4.0 but doesn't since LDC 1.5.0 in Godbolt: https://d.godbolt.org/z/3Eb47n

**Comment by kinke** [comment]
I disagree, this should be legal, because `A << int4(8)` works with LDC. The frontend implicitly casts scalars to vectors for arithmetic ops (`* 2` => `* cast(int4) 2`), but apparently not for shifts.

**Comment by p0nce** [comment]
I have no opinion about this ¯\_(ツ)_/¯
