### ISSUE TITLE
ldc 1.33: fromStringz broken with betterC (worked in 1.32)

### ISSUE THREAD

**Issue by tomerfiliba** [ldc-developers/ldc#4461]
consider this snippet (compile with `-betterC`)
```
extern(C) nothrow @nogc:

void main(int argc, char** argv) {
	import std.string: fromStringz;
    auto s = cast(string)fromStringz(argv[1]);
}
```

in 1.32 it works fine (https://godbolt.org/z/qcErPezT7) but in 1.33 it's broken (https://godbolt.org/z/Kaca615qs)

```
/opt/compiler-explorer/ldc-latest-ci/ldc/bin/../import/std/exception.d(519): Error: cannot use `throw` statements with -betterC
/opt/compiler-explorer/ldc-latest-ci/ldc/bin/../import/std/exception.d(439): Error: template instance `std.exception.bailOut!(Exception)` error instantiating
/opt/compiler-explorer/ldc-latest-ci/ldc/bin/../import/std/uni/package.d(4067):        instantiated from here: `enforce!bool`
/opt/compiler-explorer/ldc-latest-ci/ldc/bin/../import/std/uni/package.d(4407):        instantiated from here: `TrieBuilder!(bool, dchar, 1114112, sliceBits!(13LU, 21LU), sliceBits!(8LU, 13LU), sliceBits!(0LU, 8LU))`
/opt/compiler-explorer/ldc-latest-ci/ldc/bin/../import/std/uni/package.d(10660):        instantiated from here: `CodepointTrie!(bool, 8, 5, 8)`
/opt/compiler-explorer/ldc-latest-ci/ldc/bin/../import/std/uni/package.d(10749):        instantiated from here: `asTrie!(bool, 8, 5, 8)`
/opt/compiler-explorer/ldc-latest-ci/ldc/bin/../import/std/uni/package.d(7105): Error: CTFE failed because of previous errors in `graphemeExtendTrie`
/opt/compiler-explorer/ldc-latest-ci/ldc/bin/../import/std/uni/package.d(7105):        while evaluating: `static assert(!graphemeExtendTrie()['\u200d'])`
Compiler returned: 1
```

looking at the source code of `fromStringz`, i see no reason for it to throw (and either way, it's called from CTFE, not generated IR)

**Comment by kinke** [comment]
Please check DMD too, this is most likely a Phobos change.

**Comment by tomerfiliba** [comment]
DMD nightly (on godblot) seems okay: https://godbolt.org/
Not sure what version that is in relation to what's being used by ldc 1.33

**Comment by tomerfiliba** [comment]
dmd 2.102 at least works https://run.dlang.io/is/ASm4wu

**Comment by kinke** [comment]
> Not sure what version that is in relation to what's being used by ldc 1.33

DMD/Phobos v2.103.

The nightly DMD version on godbolt is v2.091.0-beta.2-master-ec39fe5...

I've tested it here with DMD v2.103.1, and that does work.
