### ISSUE TITLE
Protected template ctors cannot be accessed outside their module.

### ISSUE THREAD

**Issue by Dadoum** [ldc-developers/ldc#4767]
It is a regression as it worked in ldc2 1.34, and is preventing botan from being built.

Basic reproducer

base.d

```d 
module base;

class Base {
  protected:
    this(T)(T) {

    }
}
```

super_.d

```d
module super_;

import base;

class Derived: Base {
    this() {
        super("Example");
    }
}
````

```
$ ldc2 -i ./super_.d
./source/super.d(7): Error: constructor `base.Base.__ctor!string.this` is not accessible from module `super_`
```

**Comment by kinke** [comment]
This is an upstream regression (not sure when, but DMD v2.109 fails too), please file there.

**Comment by Dadoum** [comment]
sorry
