### PR TITLE
gen: fix implicit vector cast in binary operations

### LINKED ISSUE #3606: __vector << int produce ICE, should be illegal?
The following program crashes LDC 1.24.0 and below too:

```d
import core.simd;
void fun()
{
    int4 A;
    A = A << 8;
}
```

Output with LDC 1.24:
```
#1 with ldc beta
sext source and destination must both be a vector or neither
  %5 = sext i32 8 to <4 x i32>
in function _D7example3funFAAyaZv
LLVM ERROR: Broken function found, compilation aborted!
/opt/compiler-explorer/ldcbeta/bin/ldc2[0x33f03d4]
Compiler returned: 255
```

DMD output is correct:
```
<source>(6): Error: incompatible types for `(A) << (8)`: `__vector(int[4])` and `int`
Compiler returned: 1
```

Interestingly it used to work in LDC 1.4.0 but doesn't since LDC 1.5.0 in Godbolt: https://d.godbolt.org/z/3Eb47n

### PR DESCRIPTION
**Pull request by liushuyu**
This pull request fixes implicit vector cast in binary operations. Rather than standard integer extension, vector casts require the RHS (right-hand side) to be a vector of matching size. In this patch, a vector splat operation fills the target vector type with the original value across all the lanes/elements.

This should fix #3606.

### CODE REVIEW

**Comment by kinke** [comment]
Alternative frontend fix: https://github.com/ldc-developers/ldc/pull/4781

**Comment by liushuyu** [comment]
> Alternative frontend fix: #4781

Ah I see, then I will close this one.
