### ISSUE TITLE
Missing codegen for lambda passed as default parameter value

### ISSUE THREAD

**Issue by lodo1995** [ldc-developers/ldc#1634]
I have a project that compiles fine on DMD 1.071, but on ldc-1.1.0-alpha1 the linker complains about some undefined references. The missing code is for lambdas that only exist as default parameters to a template function:

```
struct S(T, D)
{
  T t;
  D d;
}

auto makeS(T, D)(T t, D d = (string s) {})  // looks like code for this lambda is never generated
{
  return S!(T, D)(t, d);
}

void main()
{
  auto s = makeS(1);
  s.d("foo");
}
```

I don't have an LDC compiler available right now. I encountered the error on Travis with a very big project. I wrote this small example and tried it on http://ldc.acomirei.ru/ and apparently no code is generated for symbol `pure nothrow @nogc @safe void example.makeS!(int, pure nothrow @nogc @safe void function(immutable(char)[])*).__lambda2(immutable(char)[])`.

**Comment by lodo1995** [comment]
Downloaded and tested locally. I can now 100% confirm that the code above does not link: undefined reference to the lambda function.
I think this is a *MAJOR* issue.

**Comment by lodo1995** [comment]
Ping @kinke @klickverbot 
Sorry if I bother you, but I think this issue deserves some attention (unless I'm missing something; if that's the case, please tell me, and sorry for the noise).

**Comment by JohanEngelen** [comment]
Also occurs for 0.17.1 and 1.0.0.

**Comment by JohanEngelen** [comment]
Simplified test case:
```d
void makeS(void function(string s) d = function(string s) {})  // looks like code for this lambda is never generated
{
}

void main()
{
  makeS();
}
```

We apparently don't codegen default parameter values (lambdas).

**Comment by kinke** [comment]
I had a quick look yesterday. We should probably make sure that lambdas are defined in the current module in `DtoSymbolAddress()`, right after https://github.com/ldc-developers/ldc/blob/master/gen/llvmhelpers.cpp#L1566 (`DtoDefineFunction()`). I firstly don't know how to identify lambdas though and secondly nothing about that `availableExternally` thing, so I don't know how to best tackle this.

**Comment by JohanEngelen** [comment]
I think upon codegen of a FuncDecl, we should check whether there are any default parameter values that need codegen (so no codegen on the callsite when building the argument list, but on the function definition site). Working on it.

**Comment by kinke** [comment]
What about templated types with defaulted template params?

**Comment by JohanEngelen** [comment]
Code for default template arg:
```d
struct S(void function(int i) D = function(int i) {})
{
    void ggg() {
        D(1);
    }
}

void foo()
{
    S!() s;
}
```
This actually already works.

I am going with what you propose @kinke, adding code to DtoSymbolAddress, because that is what DMD is doing (some debug tracing). I.e., the default argument function literal is emitted in the calling module, not in the called module.

**Comment by lodo1995** [comment]
Thank you guys for taking care of this.

**Comment by klickverbot** [comment]
Should be fixed in master. (@redstar: This should go into 1.1).
