### ISSUE TITLE
__asmtuple error

### ISSUE THREAD

**Issue by John-Colvin** [ldc-developers/ldc#801]
Documentation is a little sparse on the inline assembly, but shouldn't this work:

``` D
//iasmtuple.d
import ldc.llvmasm;
void main()
{
    auto a = __asmtuple!(long, long)
        ("
             movq $2, $0;
             movq $2, $1;
         ",
         "=r,=r,r", 1
        );
    assert(a.v[0] == 1 && a.v[1] == 1);
}
```

``` sh
$ ldc2 iasmtuple.d
iasmtuple.d(5): Error: special ldc inline asm is not a normal function
```

**Comment by kinke** [comment]
Working with LDC 1.5: https://godbolt.org/g/BhmirD
