### ISSUE TITLE
Weird return type error even though return types match

### ISSUE THREAD

**Issue by rjmcguire** [ldc-developers/ldc#1492]
I'm getting the below error in a non-trivial vibe.d REST API application
source/api.d(173): Error: cannot implicitly convert expression (BoolResponse(true)) of type BoolResponse to BoolResponse
source/api.d(176): Error: cannot implicitly convert expression (BoolResponse(false)) of type BoolResponse to BoolResponse

I tried to make a reduced case but compiles fine. It isn't much different from the below except that the interface and class have more methods:
`struct BoolResponse {
    bool okay;
}
enum okay = BoolResponse(true);
enum notOkay = BoolResponse(false);

interface TestI {
    BoolResponse respond(ulong i);
}
class Test : TestI {
    BoolResponse respond(ulong i) {
               // bunch of logic here
        if (i>1)
            return okay;
        else
            return notOkay;
    }
}
void main(string[] args) {
    import std.stdio;
    auto t = new Test();
    t.respond(args.length).writeln;
}`

binary    /usr/local/ldc/ldc2-1.0.0-beta2-linux-x86_64/bin/ldc2
version   1.0.0-beta2 (DMD v2.070.2, LLVM 3.8.0)
config    /usr/local/ldc/ldc2-1.0.0-beta2-linux-x86_64/etc/ldc2.conf
OVERVIEW: LDC - the LLVM D compiler

**Comment by kinke** [comment]
Sounds like a front-end error. Does it work with DMD 2.070.2?

**Comment by rjmcguire** [comment]
It works with dmd, and has since 2.068 at least. I just was trying LDC out,
so I could hopefully report bugs.

Trying to reduce a vibe app with dustmite doesn't seem to work very well
though.

**Comment by kinke** [comment]
Closing due to lack of information/reproducibility.
