### ISSUE TITLE
Error: undefined identifier `HMODULE` on Windows 10 64 bit

### ISSUE THREAD

**Issue by jordan4ibanez** [ldc-developers/ldc#4360]
I honestly have no idea what this even pertains to. Someone in the Discord said: ``"it is prolly that the thing isn't imported right or something"``. So I will just show you what's wrong in this error message:
```
C:\Users\Jordan\Documents\ldc2-1.31.0-windows-x64\bin\..\import\std\internal\windows\advapi32.d(36,9): Error: undefined identifier `HMODULE`, did you mean alias `HMODULE`?
Error C:\Users\Jordan\Documents\ldc2-1.31.0-windows-x64\bin\ldc2.exe failed with exit code 1.
```

I have created a locked snapshot of the code base here:

https://github.com/jordan4ibanez/Crafter-D/tree/368ece39eb2f584713d127321c4d8b55d28f4435

**Comment by kinke** [comment]
Does it compile with DMD v2.101 for Win64?

**Comment by jordan4ibanez** [comment]
No same error but different-ish. This is the error on DMD:
```
C:\D\dmd2\windows\bin64\..\..\src\phobos\std\internal\windows\advapi32.d(36,9): Error: undefined identifier `HMODULE`, did you mean alias `HMODULE`?
Error C:\D\dmd2\windows\bin64\dmd.exe failed with exit code 1.
```

**Comment by kinke** [comment]
It's exactly the same error, so please file it as upstream Phobos bug on https://issues.dlang.org/.

**Comment by jordan4ibanez** [comment]
> It's exactly the same error, so please file it as upstream Phobos bug on https://issues.dlang.org/. **Edit**: Sorry, as compiler bug, `HMODULE` is imported correctly in that `advapi32.d`. It's a mixed-in alias, I guess the mixin (`core.sys.windows.basetsd.DECLARE_HANDLE` - looks superfluous, just like the `TypeDef` template in that module...) gets in the way somehow.

I am very sorry, I cannot do this, it will not let me register an account on there :(

**Comment by kinke** [comment]
This was filed upstream in the meantime: https://issues.dlang.org/show_bug.cgi?id=23818
