### ISSUE TITLE
Missing etc.linux.memoryerror.registerMemoryErrorHandler

### ISSUE THREAD

**Issue by Kozzi11** [ldc-developers/ldc#1915]
When trying to compile workspace-d with ldc I get this error:

`undefined reference to _D3etc5linux11memoryerror26registerMemoryErrorHandlerFZb`

LDC libs:
`nm -D /usr/lib/libldruntime.so  | grep registerMemory`
`nm -D /usr/lib/liblphobos2.so  | grep registerMemory`

DMD libs:
`nm -D /usr/lib/libphobos2.so  | grep registerMemory
00000000004bd8b8 T _D3etc5linux11memoryerror26registerMemoryErrorHandlerFZb
00000000004bd910 T _D3etc5linux11memoryerror28deregisterMemoryErrorHandlerFZb`

**Comment by kinke** [comment]
Thanks, confirmed, it's a more general issue with our CMake script having an outdated whitelist of directories from which the runtime modules are pulled in. I'll work on a more robust black-list approach instead.

**Comment by kinke** [comment]
That particular `etc.linux.memoryerror` module causes additional, non-trivial trouble, see #1917. I'm pretty sure I recently read something about it being scheduled for deprecation (from Walter), so I won't put any more effort into it.

**Comment by 0xEAB** [comment]
just run into this, doesn’t seem deprecated yet

**Comment by kinke** [comment]
This has been reworked in druntmie v2.111: https://github.com/dlang/dmd/pull/20643

The new `registerMemoryAssertHandler()` function works with all compilers, and on most architectures. Will land with #4877.
