### ISSUE TITLE
Enums with referenced struct members result in floating point error

### ISSUE THREAD

**Issue by Philpax** [ldc-developers/ldc#1581]
Minimised test case:
```D
struct OperandFormatDescriptor
{
    string name;
}

enum OperandFormat
{
    DstSrc = OperandFormatDescriptor("DstSrc"),
}

struct OpcodeDescriptor
{
    OperandFormat operandFormat;
}

enum Opcodes
{
    // Memory
    Load = OpcodeDescriptor(OperandFormat.DstSrc),
}

void main() {}
```

results in
`test.d(8): Error: floating point constant expression expected instead of OperandFormatDescriptor("DstSrc")`

when compiled with LDC 1.0.0. This works fine with DMD 2.069 and 2.071 (the two versions of DMD I tested).

**Comment by kinke** [comment]
Thanks for the report!
