### ISSUE TITLE
LDC master, built with itself, cannot compile druntime/Phobos (Error: template <foo> cannot deduce function...)

### ISSUE THREAD

**Issue by ximion** [ldc-developers/ldc#1774]
Hello!
Due to an error we currently have an LDC Git snapshot in Debian.
(see https://tracker.debian.org/pkg/ldc )
The current built copy in the archive was build using Git revision 216c112.
Unfortunately, building a newer LDC Git version fails with
```
[ 11%] Generating gccbuiltins_s390.di
cd /build/ldc-1.1.0git20160919.77fac2d/build-static/runtime && ../bin/gen_gccbuiltins /build/ldc-1.1.0git20160919.77fac2d/build-static/runtime/gccbuiltins_s390.di s390
[ 11%] Generating std/array-debug.o
cd /build/ldc-1.1.0git20160919.77fac2d && /build/ldc-1.1.0git20160919.77fac2d/build-static/bin/ldc2 --output-o -c -I/build/ldc-1.1.0git20160919.77fac2d/runtime/druntime/src -I/build/ldc-1.1.0git20160919.77fac2d/runtime/druntime/src/gc /build/ldc-1.1.0git20160919.77fac2d/runtime/phobos/std/array.d -of/build/ldc-1.1.0git20160919.77fac2d/build-static/runtime/std/array-debug.o -w -g -link-debuglib -I/build/ldc-1.1.0git20160919.77fac2d/runtime/phobos
[ 11%] Generating std/ascii-debug.o
cd /build/ldc-1.1.0git20160919.77fac2d && /build/ldc-1.1.0git20160919.77fac2d/build-static/bin/ldc2 --output-o -c -I/build/ldc-1.1.0git20160919.77fac2d/runtime/druntime/src -I/build/ldc-1.1.0git20160919.77fac2d/runtime/druntime/src/gc /build/ldc-1.1.0git20160919.77fac2d/runtime/phobos/std/ascii.d -of/build/ldc-1.1.0git20160919.77fac2d/build-static/runtime/std/ascii-debug.o -w -g -link-debuglib -I/build/ldc-1.1.0git20160919.77fac2d/runtime/phobos
[ 11%] Generating std/base64-debug.o
cd /build/ldc-1.1.0git20160919.77fac2d && /build/ldc-1.1.0git20160919.77fac2d/build-static/bin/ldc2 --output-o -c -I/build/ldc-1.1.0git20160919.77fac2d/runtime/druntime/src -I/build/ldc-1.1.0git20160919.77fac2d/runtime/druntime/src/gc /build/ldc-1.1.0git20160919.77fac2d/runtime/phobos/std/base64.d -of/build/ldc-1.1.0git20160919.77fac2d/build-static/runtime/std/base64-debug.o -w -g -link-debuglib -I/build/ldc-1.1.0git20160919.77fac2d/runtime/phobos
[ 11%] Generating std/bigint-debug.o
cd /build/ldc-1.1.0git20160919.77fac2d && /build/ldc-1.1.0git20160919.77fac2d/build-static/bin/ldc2 --output-o -c -I/build/ldc-1.1.0git20160919.77fac2d/runtime/druntime/src -I/build/ldc-1.1.0git20160919.77fac2d/runtime/druntime/src/gc /build/ldc-1.1.0git20160919.77fac2d/runtime/phobos/std/bigint.d -of/build/ldc-1.1.0git20160919.77fac2d/build-static/runtime/std/bigint-debug.o -w -g -link-debuglib -I/build/ldc-1.1.0git20160919.77fac2d/runtime/phobos
/build/ldc-1.1.0git20160919.77fac2d/runtime/phobos/std/conv.d(298): Error: template std.conv.toImpl cannot deduce function from argument types !(string)(const(char)[]), candidates are:
/build/ldc-1.1.0git20160919.77fac2d/runtime/phobos/std/conv.d(364):        std.conv.toImpl(T, S)(S value) if (isImplicitlyConvertible!(S, T) && !isEnumStrToStr!(S, T) && !isNullToStr!(S, T))
/build/ldc-1.1.0git20160919.77fac2d/runtime/phobos/std/conv.d(478):        std.conv.toImpl(T, S)(ref S s) if (isRawStaticArray!S)
/build/ldc-1.1.0git20160919.77fac2d/runtime/phobos/std/conv.d(494):        std.conv.toImpl(T, S)(S value) if (!isImplicitlyConvertible!(S, T) && is(typeof(S.init.opCast!T()) : T) && !isExactSomeString!T && !is(typeof(T(value))))
/build/ldc-1.1.0git20160919.77fac2d/runtime/phobos/std/conv.d(545):        std.conv.toImpl(T, S)(S value) if (!isImplicitlyConvertible!(S, T) && is(T == struct) && is(typeof(T(value))))
/build/ldc-1.1.0git20160919.77fac2d/runtime/phobos/std/conv.d(594):        std.conv.toImpl(T, S)(S value) if (!isImplicitlyConvertible!(S, T) && is(T == class) && is(typeof(new T(value))))
/build/ldc-1.1.0git20160919.77fac2d/runtime/phobos/std/conv.d(298):        ... (9 more, -v to show) ...
/build/ldc-1.1.0git20160919.77fac2d/runtime/phobos/std/conv.d(3672): Error: template instance std.conv.to!string.to!(const(char)[]) error instantiating
/build/ldc-1.1.0git20160919.77fac2d/runtime/phobos/std/conv.d(3656):        instantiated from here: textImpl!(string, string, const(char)[])
/build/ldc-1.1.0git20160919.77fac2d/runtime/phobos/std/format.d(913):        instantiated from here: text!(string, const(char)[])
/build/ldc-1.1.0git20160919.77fac2d/runtime/phobos/std/bigint.d(803):        instantiated from here: FormatSpec!char
/build/ldc-1.1.0git20160919.77fac2d/runtime/phobos/std/range/primitives.d(2238): Error: template std.utf.decode cannot deduce function from argument types !()(const(char)[], ulong), candidates are:
/build/ldc-1.1.0git20160919.77fac2d/runtime/phobos/std/utf.d(1007):        std.utf.decode(Flag useReplacementDchar = UseReplacementDchar.no, S)(auto ref S str, ref size_t index) if (!isSomeString!S && isRandomAccessRange!S && hasSlicing!S && hasLength!S && isSomeChar!(ElementType!S))
/build/ldc-1.1.0git20160919.77fac2d/runtime/phobos/std/utf.d(1026):        std.utf.decode(Flag useReplacementDchar = UseReplacementDchar.no, S)(auto ref S str, ref size_t index) if (isSomeString!S)
/build/ldc-1.1.0git20160919.77fac2d/runtime/phobos/std/conv.d(1950): Error: template instance std.range.primitives.front!(const(char)) error instantiating
/build/ldc-1.1.0git20160919.77fac2d/runtime/phobos/std/format.d(978):        instantiated from here: parse!(int, const(char)[])
/build/ldc-1.1.0git20160919.77fac2d/runtime/phobos/std/bigint.d(803):        instantiated from here: FormatSpec!char
/build/ldc-1.1.0git20160919.77fac2d/runtime/phobos/std/range/primitives.d(2092): Error: static assert  "Bad template constraint."
/build/ldc-1.1.0git20160919.77fac2d/runtime/phobos/std/conv.d(1964):        instantiated from here: popFront!(const(char))
/build/ldc-1.1.0git20160919.77fac2d/runtime/phobos/std/format.d(978):        instantiated from here: parse!(int, const(char)[])
/build/ldc-1.1.0git20160919.77fac2d/runtime/phobos/std/bigint.d(803):        instantiated from here: FormatSpec!char
runtime/CMakeFiles/phobos2-ldc-debug.dir/build.make:105: recipe for target 'runtime/std/bigint-debug.o' failed
make[3]: *** [runtime/std/bigint-debug.o] Error 1
```

I think I have seen this before and it didn't happen when building with a released LDC.
It would be awesome if this problem could be fixed somehow...

**Comment by ximion** [comment]
I tried this again with the released LDC 1.1.0 beta 2: Build of LDC Git succeeds, but when I try to compile the compiler with the result of the first run, I run into the issue described above.

**Comment by kinke** [comment]
I'll see if I can reproduce it here.

**Comment by ximion** [comment]
That would be awesome, since a large amount of stuff depends on LDC being ready, and we are running out of time to get LDC into shape to be in the next Debian release...

If you are on any Debian-based derivative, you could easily reproduce this with the packages.
(Sources here: https://anonscm.debian.org/git/pkg-d/ldc.git/ )

**Comment by kinke** [comment]
I can reproduce it here on Windows too, same errors. :(

**Comment by kinke** [comment]
As much as I'd like seeing 1.1 in the next Debian release (!), we shouldn't rush - i.e., 1.1 should be released first, maybe even with 1+ week out in the wild to check for serious issues. ;)

> a large amount of stuff depends on LDC being ready

If so, we could really use some more manpower over here. </complaining>

**Comment by kinke** [comment]
I find it hard to make sense of this. Why would the D host compiler used to compile LDC cause these template issues?

**Comment by ximion** [comment]
The main issue is that due to a mistake we have a Git snapshot of LDC in Debian, which is quite painful and should never have happened...

**Comment by kinke** [comment]
So if the previous https://github.com/ldc-developers/ldc/commit/216c1126d1893f5987ee1443a0dcd06926151e66 worked, it's [the last DDMD merge](https://github.com/ldc-developers/ldc/commit/9d99f59acd5e4c0bbc64a8f156e7d44e2f4bbe45) that broke it (fails too, just verified).

**Comment by kinke** [comment]
https://github.com/ldc-developers/ldc/commit/4e495c567894de2c041691db9bd38411a826c0aa, the commit before the DDMD merge, can't build the merge either. So my best guess is that the merge uncovers an older LDC bug which hasn't shown up until now.

**Comment by kinke** [comment]
'Older' bug meaning something that crept in after 1.1.0-beta2, as that one's used by Travis for the LLVM 3.8 Linux job. Any `git bisect` volunteers? ;)

**Comment by JohanEngelen** [comment]
bisecting...

For easy future reference, using this script with `git bisect run`:
```
git submodule update
cd build39release
ninja clean
ninja -j 2
if [ "$?" != "0" ]; then
    exit 125
fi

cd ..
cd build39self
ninja clean
ninja -j 2

if [ "$?" != "0" ]; then
    exit 1
fi
```

**Comment by JohanEngelen** [comment]
Commit e711deac1bb422d694aa7c6c04a4d559b8ffe614 works.

Commit caf5397f6f948537010a34943333dd1d4ab23bc0 starts failing self-build with a few of these:
```
/Users/johan/ldc/johan/runtime/phobos/std/internal/test/dummyrange.d(188): Error: template instance std.internal.test.dummyrange.DummyRange!(cast(ReturnBy)0, cast(Length)0, cast(RangeType)1) does not match template declaration DummyRange(ReturnBy _r, Length _l, RangeType _rt, T = uint[]) if (isArray!T)
...
```
Note: it's a different error than the error in OP.

**Comment by kinke** [comment]
Thanks Johan! Too bad it's that huge commit. :(

**Comment by JohanEngelen** [comment]
> I find it hard to make sense of this. Why would the D host compiler used to compile LDC cause these template issues?

This.
So apparently we miscompile something, and it manifests in funny template issues. But how does the exception handling stuff cause that??

**Comment by kinke** [comment]
I bet it's [this nested scope(exit) change](https://github.com/ldc-developers/ldc/commit/9d99f59acd5e4c0bbc64a8f156e7d44e2f4bbe45#diff-9073f018e95473d6205f3bab943316dcR692), in combination with [2 forward-referenced goto's](https://github.com/ldc-developers/ldc/commit/9d99f59acd5e4c0bbc64a8f156e7d44e2f4bbe45#diff-9073f018e95473d6205f3bab943316dcR706) for which it probably isn't applied anymore.

**Comment by kinke** [comment]
Well, by looking at the IR for the 5 touched modules in the front-end merge commit, only `ddmd/expression.d` is compiled differently for https://github.com/ldc-developers/ldc/commit/e711deac1bb422d694aa7c6c04a4d559b8ffe614 and https://github.com/ldc-developers/ldc/commit/caf5397f6f948537010a34943333dd1d4ab23bc0. It does smell like a bug wrt. unresolved gotos and clean-ups, but it's not obvious after a first look.

**Comment by kinke** [comment]
Fixed by https://github.com/ldc-developers/ldc/pull/1803 (no test yet).

**Comment by ximion** [comment]
Thanks a lot!
Let's see if this can help to unblock the package at Debian :-)

**Comment by ximion** [comment]
Maybe having the CI test whether LDC can compile itself would make some sense too...
