### ISSUE TITLE
Incompatible function/seed/element: a.main.__lambda1/int/string

### ISSUE THREAD

**Issue by nu8** [ldc-developers/ldc#3581]
With this file:

~~~d
import std.algorithm, std.stdio;

void main() {
   auto a = ["May", "June"];
   // example 1
   auto n1 = reduce!((n, s) => n + s.length)(0, a);
   // example 2
   auto n2 = fold!((n, s) => n + s.length)(a, 0);
   // print
   writeln(n1 == 7 && n2 == 7);
}
~~~

Works fine with DMD 2.94. However With LDC 1.23, I get this:

~~~
C:\ldc2\bin\..\import\std\algorithm\iteration.d(3775): Error: static assert:
   "Incompatible function/seed/element: a.main.__lambda1/int/string"
C:\ldc2\bin\..\import\std\algorithm\iteration.d(3759):        instantiated from
   here: reduceImpl!(false, string[], int)
C:\ldc2\bin\..\import\std\algorithm\iteration.d(3743):        instantiated from
   here: reducePreImpl!(string[], int)
a.d(6):        instantiated from here: reduce!(int, string[])
~~~~

**Comment by thewilsonator** [comment]
This is an issue with the  2.93 version of phobos which LDC 1.23 ships with. DMD 2.93 also fails with the same error.

**Comment by nu8** [comment]
ok? So do you guys have a nightly or something? Cause I think I am using the latest release:

https://github.com/ldc-developers/ldc/releases

**Comment by kinke** [comment]
There's a 1.24 beta1 at the top. ;)

**Comment by nu8** [comment]
ah, I didnt see it because its pre-release - thanks

**Comment by nu8** [comment]
Umm:

~~~
PS D:\Desktop> ldc2.exe --version
LDC - the LLVM D compiler (1.24.0-beta1):

PS D:\Desktop> ldc2.exe -run a.d
C:\ldc2\bin\..\import\std\algorithm\iteration.d(3775): Error: static assert:
   "Incompatible function/seed/element: a.main.__lambda1/int/string"
C:\ldc2\bin\..\import\std\algorithm\iteration.d(3759):        instantiated from
   here: reduceImpl!(false, string[], int)
C:\ldc2\bin\..\import\std\algorithm\iteration.d(3743):        instantiated from
   here: reducePreImpl!(string[], int)
a.d(6):        instantiated from here: reduce!(int, string[])
~~~

**Comment by kinke** [comment]
You're most likely comparing DMD with default 32-bit output vs. LDC with 64-bit. Try adding `-m64` to DMD. Fix it by using `size_t(0)` as seeds.

**Comment by nu8** [comment]
@kinke thanks, that was the problem. That means that this comment by @thewilsonator is invalid:

> This is an issue with the 2.93 version of phobos which LDC 1.23 ships with. DMD 2.93 also fails with the same error.

as the problem was nothing to do with what version I had. I would caution @thewilsonator from closing so quickly without due diligence, he literally closed the issue in 4 minutes after it was opened.
