### ISSUE TITLE
Release v1.5

### ISSUE THREAD

**Issue by kinke** [ldc-developers/ldc#2369]
I'm in a bit of a hurry and would like to release beta1 these days; 1.6 is already looking good, and DMD just released the first 2.077 beta (I've lately clearly aimed at reducing the gap considerably, but it's hard to keep up with DMD's recent release pace).

**Comment by joakim-noah** [comment]
I'm seeing this warning a lot when building druntime and phobos for ldc 1.5, on both linux/x64 and Android/ARM, worth doing something about?
```
(5): Warning: skipping definition of function `__entrypoint._Dmain` due to previous definition for the same mangled name: _Dmain
Warning: skipping definition of function `rt.arraydouble._arraySliceSliceAddass_d` due to previous definition for the same mangled name: _arraySliceSliceAddass_d
```
Other than that, beta1 sounds good to me, all well on Android/ARM with ldc 1.5.

**Comment by kinke** [comment]
That warning hasn't caught my attention yet - only the warning itself is new, the multiple definitions were already there before.

**Comment by kinke** [comment]
beta1 tagged. @JohanEngelen: you know the drill :)

**Comment by kinke** [comment]
@klickverbot: Could you create the OSX archive as Johan seems unavailable?

**Comment by JohanEngelen** [comment]
Building the OSX binaries now (vacation).

**Comment by joakim-noah** [comment]
I've submitted a pull to have a native Android ldc 1.5 beta for the Termux app, termux/termux-packages#1323, will add some info to the beta release when that gets in.

**Comment by JohanEngelen** [comment]
macOS binaries are up. I'm not 100% sure that they work on macOS versions before 10.13 (High Sierra)... can someone check?

**Comment by klickverbot** [comment]
Hello World seems to compile and run on 10.12.

**Comment by joakim-noah** [comment]
The beta release has been put in draft status again, doesn't show up publicly anymore.  Should we make it public again?

**Comment by JohanEngelen** [comment]
Oh sorry, I did that probably :( sorry

**Comment by joakim-noah** [comment]
No problem, we haven't announced it yet.  I just couldn't download the source zip file when the release is in draft status, so I mentioned it.

**Comment by kinke** [comment]
Announced now (had a bad headache yesterday).

**Comment by kinke** [comment]
Ready for the final? I think master is looking very good.

**Comment by kinke** [comment]
@JohanEngelen: OSX package pls. :)
I'll provide a Debian Jessie armhf package later; I unfortunately have to recompile LLVM to make it output ARMv6 code by default (#1988)...

**Comment by kinke** [comment]
@klickverbot: Please consider doing the OSX package this time.

**Comment by joakim-noah** [comment]
I've submitted a pull to update the native Android package, termux/termux-packages#1731, will add a line to the release notes once that's in.  Also, ran the stdlib tests on Android/ARM cross-compiled by `ldc-build-runtime` using the official linux/x64 release build without a problem.

**Comment by klickverbot** [comment]
@kinke: Building. Did @JohanEngelen use any special flags?

**Comment by kinke** [comment]
I can only guess he didn't, as I'd think he's the type of guy who would have fixed ldc-scripts in that case. ;)

**Comment by klickverbot** [comment]
LDC doesn't build using the `ldc2-packaging` script on Xcode 9/macOS 10.12 because of the `_futimens` issue. HAVE_FUTIMENS needs to be set in the scripts until this is fixed (in LLVM 5.0.1)?

**Comment by joakim-noah** [comment]
My ldc 1.5 termux pull got merged, just waiting for the Android/ARM package to be built before updating the release notes.  No need to wait on that before announcing ldc 1.5 though.

Heh, great to see master caught up to the latest dmd 2.076.1 release and the 1.6 beta queued up, nice work, @kinke.  I think it's worth getting the beta out earlier given the shrinking D release cycle, even if it's more of an alpha because it's still on master and getting worked on.

**Comment by kinke** [comment]
Thx Joakim. I'm also for a quick release of the next beta (just waiting on what others think about the JIT feature integration) as master IMO appears in good shape and 2.077 is imminent.

**Comment by klickverbot** [comment]
I'll fix this and upload the packages later this evening, if Johan doesn't beat me to it.

**Comment by klickverbot** [comment]
Still doesn't (re)build:
```
[ 20%] Generating bin/ldmd2.o
[ 20%] Generating bin/ldmd2
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
LLVM ERROR: Function Import: link error
LLVM ERROR: Function Import: link error
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

@JohanEngelen: Do I need to disable LTO? Is this supposed to work?

**Comment by JohanEngelen** [comment]
@klickverbot I think I built without LTO yeah. There is an LTO bug somewhere that I haven't looked into yet... Otherwise nothing special.

**Comment by kinke** [comment]
I hope 'nothing special' includes not having to additionally set `USE_LIBCPP` given David's warning. Please fix ldc-scripts to reduce chances of further incidents in the future and get that file finally uploaded, it surely doesn't take more than an hour? The ARM package came to life after 60 hours of cumulated building.

**Comment by klickverbot** [comment]
LDC finally built now. Just need to build dub/tools.

**Comment by klickverbot** [comment]
OS X archive uploaded at last, built using `BUILD_WITH_LTO=off` (and `HAVE_FUTIMENS=0`, but that's committed).

**Comment by kinke** [comment]
Alright, thanks a lot. It's finally officially announced.

**Comment by joakim-noah** [comment]
When you built the stdlib for armhf, did you specify a CPU or no problem like I had with Android/ARM with the generic CPU?

**Comment by kinke** [comment]
No problem as it selects a default CPU for ARMv6 IIRC.

**Comment by joakim-noah** [comment]
OK, going to mention the issue in release notes for Android, wondered if it was needed for the armhf compiler too, guess not.

**Comment by joakim-noah** [comment]
I wanted to try out the new linux/armhf build, so [I setup a kind of chroot that doesn't require root on Android/ARM using this proot package](https://wiki.termux.com/wiki/PRoot), extracted an ARM distro, and built and ran the stdlib tests with `ldc-build-runtime`.  All the druntime tests pass in release mode, but the phobos test runner segfaults.

Could just be an issue with my proot setup, I'll investigate further and let you know.

**Comment by joakim-noah** [comment]
gdb doesn't appear to be working properly in proot, though it works in the termux app, so I'm not sure how to track down the segfault.  Building and running the tests for some individual phobos modules, I see that the stack corruption issue for the `std.random` tests with `-O1 -enable-inlining` carries over to linux/armhf too.  @kinke, were you able to run the linux/armhf tests and what were your results?

**Comment by kinke** [comment]
See https://github.com/ldc-developers/ldc/issues/2403#issuecomment-342590190 with respect to the druntime/Phobos unittests.
1-2 lit-tests failed IIRC, but only because they assume an x86 target (DMD-style inline asm without proper check etc.).
I started a dmd-testsuite-debug run (which also required a tiny patch as the OS bitness couldn't be inferred IIRC) but aborted it after quite some hours, the emulator's slowness got on my nerves. They were looking good until that point though IIRC.

**Comment by joakim-noah** [comment]
OK, good to hear the phobos test runner ran, probably some proot issue on my end.
