### ISSUE TITLE
[REG 1.42] Can supposedly index AA with mismatching key type

### ISSUE THREAD

**Issue by kinke** [ldc-developers/ldc#5060]
This fails with both beta1 and beta2 of LDC v1.42, but has worked with v1.41 and also works with DMD v2.112.0 and current DMD stable:
```D
enum E { a }
bool[E] aa;
static assert(!__traits(compiles, aa[0])); // would compile since v1.42?!
```

Of course it wouldn't really compile:
```
core/internal/newaa.d(172): Error: cannot implicitly convert expression `key` of type `int` to `E`
```

Weird that this seems to be LDC-specific.

**Comment by kinke** [comment]
Oh, this might be a duplicate of https://github.com/dlang/dmd/issues/22281, as I've cherry-picked https://github.com/dlang/dmd/pull/22208 from DMD master (required to compile the Phobos unittests with `-de` IIRC), which seems to have introduced it.

**Comment by kinke** [comment]
Nope, apparently no duplicate, but another regression introduced in dlang/dmd#22208 - DMD master fails too.
