### ISSUE TITLE
Linking fails with "unresolved external symbol main" on subsystem:windows

### ISSUE THREAD

**Issue by KytoDragon** [ldc-developers/ldc#3436]
If i pass the "subsystem:windows" option for Windows to the msvc linker, i get a link error stating that "main" cannot be found.
Example:
```
void main() {}
```

dub.json:
```
{
	"name": "d-test",
	"lflags-windows": ["/entry:mainCRTStartup", "/subsystem:windows"],
}
```
Output when running dub:
```
libcmt.lib(exe_main.obj) : error LNK2019: unresolved external symbol main referenced in function "int __cdecl __scrt_common_main_seh(void)" (?__scrt_common_main_seh@@YAHXZ)
.dub\build\application-debug-windows-x86_64-ldc_2092-7A23D16BC2E3C27FAA765158DD91605C\d-test.exe : fatal error LNK1120: 1 unresolved externals
Error: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\bin\HostX64\x64\link.exe failed with status: 1120
FAIL .dub\build\application-debug-windows-x86_64-ldc_2092-7A23D16BC2E3C27FAA765158DD91605C\ d-test executable
C:\Dev\ldc2\bin\ldc2.exe failed with exit code 1.
```
Running 1.22.0-beta1 on Windows 10 with Visual Studio 2019, both x86 and x64 builds.
This worked fine on ldc 1.16.0, on version 1.21.0 the default linker is lld, which results in the following output:
```
lld-link: error: undefined symbol: main
>>> referenced by vcruntime140.lib(msvcrt_stub1.obj):($LN3)
Error: linking with LLD failed
C:\Dev\ldc2\bin\ldc2.exe failed with exit code 1.
```

**Comment by KytoDragon** [comment]
Nevermind. LDC switched to using the wide-char entrypoints, so now the options need to be:
```
{
	"name": "d-test",
	"lflags-windows": ["/entry:wmainCRTStartup", "/subsystem:windows"],
}
```
