### ISSUE TITLE
Musl fails due to std.regex import

### ISSUE THREAD

**Issue by andre2007** [ldc-developers/ldc#2911]
I am not sure whether this belongs to Phobos or LDC. I have a small application which I compile using Musl and ldc-1.13.0-beta1.

```
/+ dub.sdl:
    name "application"
    dflags "-mtriple=x86_64-unknown-linux-musl" platform="ldc"
+/

import std.regex;
void main(){}
```

it fails due to the std.regex import:

```
.dub/obj/application.o:cgi.d:function _D3std5stdio4File17LockingTextWriter__T3putTyaZQiMFNfyaZ12trustedFPUTCFNbNiNeiPS4core4stdcQDg8_IO_FILEZi: error: undefined reference to '_D3std5stdio14fputc_unlockedFNbNiiPS4core4stdcQBo8_IO_FILEZi'
.dub/obj/application.o:cgi.d:function _D3std5stdio4File17LockingTextWriter__T3putTyaZQiMFNfyaZ13trustedFPUTWCFNbNiNewPS4core4stdcQDh8_IO_FILEZi: error: undefined reference to '_D3std5stdio15fputwc_unlockedFNbNiwPS4core4stdcQBp8_IO_FILEZi'
.dub/obj/application.o:cgi.d:function _D3std5stdio4File17LockingTextWriter__T3putTaZQhMFNfaZ12trustedFPUTCFNbNiNeiPS4core4stdcQDe8_IO_FILEZi: error: undefined reference to '_D3std5stdio14fputc_unlockedFNbNiiPS4core4stdcQBo8_IO_FILEZi'
.dub/obj/application.o:cgi.d:function _D3std5stdio4File17LockingTextWriter__T3putTaZQhMFNfaZ13trustedFPUTWCFNbNiNewPS4core4stdcQDf8_IO_FILEZi: error: undefined reference to '_D3std5stdio15fputwc_unlockedFNbNiwPS4core4stdcQBp8_IO_FILEZi'
.dub/obj/application.o:cgi.d:function _D3std5stdio4File17LockingTextWriter__T3putTxaZQiMFNfxaZ12trustedFPUTCFNbNiNeiPS4core4stdcQDg8_IO_FILEZi: error: undefined reference to '_D3std5stdio14fputc_unlockedFNbNiiPS4core4stdcQBo8_IO_FILEZi'
.dub/obj/application.o:cgi.d:function _D3std5stdio4File17LockingTextWriter__T3putTxaZQiMFNfxaZ13trustedFPUTWCFNbNiNewPS4core4stdcQDh8_IO_FILEZi: error: undefined reference to '_D3std5stdio15fputwc_unlockedFNbNiwPS4core4stdcQBp8_IO_FILEZi'
collect2: error: ld returned 1 exit status
Error: /usr/bin/gcc failed with status: 1
/home/user/dlang/ldc-1.13.0-beta1/bin/ldc2 failed with exit code 1.
```

**Comment by joakim-noah** [comment]
Yeah, that's not going to work, as you're linking against a Phobos built for glibc and glibc itself. If you want to cross-compile from a glibc distro like Arch, install the Musl libc, rebuild druntime and Phobos to use it, [as shown in the first example on the wiki page](https://wiki.dlang.org/Building_LDC_runtime_libraries#Usage_for_cross-compilation), and link against the Musl libc.

**Comment by andre2007** [comment]
Thanks :)

**Comment by andre2007** [comment]
I installed the packages ```musl clang cmake``` (Ubuntu 18.04) and execute
```CC=musl-clang ldc-build-runtime --dFlags="-w;-mtriple=x86_64-alpine-linux-musl"```

but get the error: Could not find compiler set in environment variable CC: musl-clang.
What package is needed in addition?

**Comment by joakim-noah** [comment]
Those instructions are for Arch. Looking up the relevant packages on Ubuntu now, it looks like you need the `musl-tools` package, then use the `musl-gcc` wrapper as `CC`, as they don't provide one for clang.

**Comment by andre2007** [comment]
Thanks a lot.
Command ```CC=musl-gcc ldc-build-runtime --dFlags="-w;-mtriple=x86_64-alpine-linux-musl"```
fails with
```
[ 20%] Linking C shared library lib/libdruntime-ldc-debug-shared.so
/usr/bin/ld: CMakeFiles/druntime-ldc-debug-shared.dir/druntime/src/core/stdc/errno.c.o: relocation R_X86_64_PC32 against symbol `__errno_location' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
CMakeFiles/druntime-ldc-debug-shared.dir/build.make:1605: recipe for target 'lib/libdruntime-ldc-debug-shared.so.2.0.83' failed
make[2]: *** [lib/libdruntime-ldc-debug-shared.so.2.0.83] Error 1
CMakeFiles/Makefile2:300: recipe for target 'CMakeFiles/druntime-ldc-debug-shared.dir/all' failed
make[1]: *** [CMakeFiles/druntime-ldc-debug-shared.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
```

Is this an issue with the ldc-build-runtime tool?

**Comment by joakim-noah** [comment]
No, could be a regression in cross-compiling for Musl, as it's reproducible for me with 1.12 too, or Ubuntu's Musl tools expects you to pass C flags that Arch does for you. These alternate toolchains aren't tested much.

I do run all the tests on Alpine with every major release when producing the native Alpine build, but didn't hit these natively. I'll look into it and let you know, another strange error when cross-compiling `std.file` too.

**Comment by kinke** [comment]
> Is this an issue with the ldc-build-runtime tool?

Should be trivial to work around with `--cFlags=-fPIC` in the ` ldc-build-runtime` cmdline.

**Comment by andre2007** [comment]
Thanks a lot.. With --cFlags=-fPIC I also now hitting mentioned std.file error

```
std/file.d-mixin-1189(1189): Error: mutable method core.sys.posix.sys.stat.stat_t.st_ctime is not callable using a const object
std/file.d-mixin-1189(1189):        Consider adding const or inout to core.sys.posix.sys.stat.stat_t.st_ctime
std/file.d(3931): Error: template instance `std.file.statTimeToStdTime!'c'` error instantiating
std/file.d-mixin-1189(1189): Error: mutable method core.sys.posix.sys.stat.stat_t.st_atime is not callable using a const object
std/file.d-mixin-1189(1189):        Consider adding const or inout to core.sys.posix.sys.stat.stat_t.st_atime
std/file.d(3938): Error: template instance `std.file.statTimeToStdTime!'a'` error instantiating
std/file.d-mixin-1189(1189): Error: mutable method core.sys.posix.sys.stat.stat_t.st_mtime is not callable using a const object
std/file.d-mixin-1189(1189):        Consider adding const or inout to core.sys.posix.sys.stat.stat_t.st_mtime
std/file.d(3945): Error: template instance `std.file.statTimeToStdTime!'m'` error instantiating
```

**Comment by thewilsonator** [comment]
If you don't want to try an trawl through that you might want to consider cherrypicking 
https://github.com/dlang/dmd/pull/8677

**Comment by joakim-noah** [comment]
OK, I hit that `std.file` issue with ldc 1.12 on Alpine also: patched it back then and forgot to upstream my small change, since I went into all the Android/x86-x64 and emulated TLS work.

Here's the druntime patch I used to get Phobos to work with Musl:
```
--- a/src/core/sys/posix/sys/stat.d	2018-10-14 23:07:47.000000000 +0530
+++ b/src/core/sys/posix/sys/stat.d	2018-10-14 21:04:37.000000000 +0530
@@ -1348,11 +1348,11 @@
         timespec st_atim;
         timespec st_mtim;
         timespec st_ctim;
-        extern(D) @safe @property
+        extern(D) @safe @property pure nothrow
         {
-            ref time_t st_atime() return { return st_atim.tv_sec; }
-            ref time_t st_mtime() return { return st_mtim.tv_sec; }
-            ref time_t st_ctime() return { return st_ctim.tv_sec; }
+            time_t st_atime() const return { return st_atim.tv_sec; }
+            time_t st_mtime() const return { return st_mtim.tv_sec; }
+            time_t st_ctime() const return { return st_ctim.tv_sec; }
         }
         long[3] __unused;
     }

```
Applying that patch to the downloaded druntime in `ldc-build-runtime.tmp/ldc-src/runtime/druntime`, disabling the shared runtime libraries, and resetting CMake gets the static runtime libraries to build, with this command:
```
CC=musl-gcc ./ldc2-1.12.0-linux-x86_64/bin/ldc-build-runtime
--dFlags="-w;-mtriple=x86_64-alpine-linux-musl" --reset
BUILD_SHARED_LIBS=OFF
```
That gets a simple executable to work:
```
CC=musl-gcc ./ldc2-1.12.0-linux-x86_64/bin/ldc2
-mtriple=x86_64-alpine-linux-musl -L-Lldc-build-runtime.tmp/lib sieve.d

./sieve
```
As for shared libraries, `-fPIC` is not the issue, as CMake adds that by default when compiling C files, and I don't see anything relevant in [the `musl-clang` wrapper that Arch uses](https://git.musl-libc.org/cgit/musl/tree/tools/musl-clang.in), so you may have to experiment with that a bit, if you want it to work. It worked fine for me with the `musl-clang` wrapper that Musl provides and that Arch's Musl package sets up, but the Ubuntu package doesn't.

**Comment by andre2007** [comment]
Thank you for your great work.
I think this issue can be closed.

**Comment by kinke** [comment]
Let's keep it open, in order not to forget to upstream the druntime patch, and ideally look into the `-fPIC` thing too.

**Comment by kinke** [comment]
Wrt. `-fPIC`: we set each CMake library target's `POSITION_INDEPENDENT_CODE=ON` if the `TARGET_SYSTEM` includes `Linux` [here](https://github.com/ldc-developers/ldc/blob/master/runtime/CMakeLists.txt#L485-L488), so that looks fine.

**Comment by kinke** [comment]
Upstream PR: https://github.com/dlang/druntime/pull/2481
