### ISSUE TITLE
Cannot build dmd master with ldc master

### ISSUE THREAD

**Issue by Temtaime** [ldc-developers/ldc#2849]
..\dmd-master\dmd\backend\cod4.d(48,25): Error: Global variable type does not match previous declaration with same mangled name: ?dblreg@@3PAIB
..\dmd-master\dmd\backend\cod4.d(48,25):        Previous IR type: [4 x i32]
..\dmd-master\dmd\backend\cod4.d(48,25):        New IR type:      [4 x i32]

__gshared const uint[4] dblreg = [ BX,DX,cast(uint)-1,CX ];

Removing the initializer causes the error to go

**Comment by kinke** [comment]
Isolated into a single module, it's working fine with v1.11 and v1.12-beta1 (the function-local global is `extern(D)`-mangled appropriately => no collision):

```D
extern(C++):

__gshared const uint[4] dblreg = [ 1, 2, 3, 4 ];

private uint foo()
{
    static const uint[4] dblreg = [ 1, 2, 3, 1 ];
    return dblreg[0] + dblreg[3];
}
```

**Comment by Temtaime** [comment]
So are you able to reproduce it ?

**Comment by kinke** [comment]
Yep, I'm now able to reproduce the error when compiling the DMD master backend with LDC v1.11 on Windows (both 32 and 64 bits).

**Comment by kinke** [comment]
Minimized, not Windows-specific:
```D
extern(C++):

__gshared const int dblreg = 1;

pragma(mangle, dblreg.mangleof)
extern __gshared const int bla;
```

**Comment by kinke** [comment]
The 2 declarations differ in IR const-ness - we only declare const/immutable globals with a non-void initializer as true constants (not initializable in static ctor), so any `extern` forward declaration is currently treated as non-IR-const. Knowing how to emit it would require knowledge about the actual definition. As it also affects mangling, we cannot even burden the user ('only forward-declare as const/immutable if it's a true constant')...

**Comment by kinke** [comment]
Clang defines and forward-declares a `const int[4]` as IR constant.

**Comment by rainers** [comment]
The dblreg issue seems fixed with LDC 1.12.0-beta2, but I now get

..\dmd\backend\ty.d(337): error : Global variable type does not match previous declaration with same mangled name: `tystring`
1>  ..\dmd\backend\ty.d(337):        Previous IR type: [92 x i8*]
1>  ..\dmd\backend\ty.d(337):        New IR type:      [92 x i8*]

There is only one extern declaration on the D side:
```
extern (C) { extern __gshared const char*[TYMAX] tystring; }
```

**Comment by kinke** [comment]
@rainers: Yeah, one 'normal' declaration, but there's this too apparently: https://github.com/dlang/dmd/blob/9472260608e60a27fd1c79667a3a22867f68fa92/src/dmd/backend/optabgen.c#L1110

The definition differs in constness (`const(char)*[N]` vs. `const char*[N]`).

**Comment by rainers** [comment]
Ah, thanks for explanation. Sorry for the noise, opened a dmd PR: https://github.com/dlang/dmd/pull/8791
